#!/bin/sh

ROOT=$(pwd)

rm -rf target/bela

nim c \
	-d:bela -d:danger \
	--gc:arc \
	--noMain:on \
	--cpu:arm --os:linux \
	--cincludes:~/Bela/include \
	-c --nimcache:target/bela \
	src/bela.nim || exit 1

cp src/render.cpp target/bela/

cd ~/Bela/scripts

./build_project.sh $ROOT/target/bela --force -m 'CFLAGS="-I/root/nim-1.4.8/lib" LDLIBS="-lsoundpipe"'
