#!/bin/sh

# ./render <duration in seconds> <path/to/output.wav>

# To render as fast as we can.
NIM_FLAGS="--gc:orc -d:danger --passC:-ffast-math --cincludes:dsp/ffi/kissfft"

nim c $NIM_FLAGS -r -o:target/render src/render.nim $@
