#!/bin/sh

# ./render <duration in seconds> <path/to/output.wav>

# To render as fast as we can.
NIM_FLAGS="--mm:arc -d:danger --passC:-ffast-math --cincludes:dsp/ffi/mufft --passC:-flto --passL:-flto"

nim c $NIM_FLAGS -r -o:target/render src/render.nim $@
