#!/bin/sh

# This script is just for the development, it assumes that the session changes
# are only for testing other code changes and don't need to be preserved.

# dlopen tries really hard to reuse shared objects. The simplest way I've found
# to workaround it on macOS is to build the library with a different name each
# time. Just "double-buffer" copying as clive does didn't work, I assume because
# not only the filename/inode is checked but LC_ID_DYLIB baked into the file
# too. We also have to randomize the naming and remove unloaded libs to
# make it work.

rm target/session.so.*
nim c --app:lib -o:target/session.so.$RANDOM src/session.nim

fswatch -o src | while read num; do
	rm target/session.so.*
	nim c --app:lib -o:target/session.so.$RANDOM src/session.nim
done
