#!/bin/sh

# Loop is an attempt to minimize disruption to the performance caused by
# crashing the server. There will be a silent gap, and state is lost
# but at least we can focus on correcting the session code rather than
# on restarting server manually.
while true; do
	# --dac:N is output device index, defaults to the system's one.
	# --adc:N is input device index
	# Server lists indexed devices upon start.
	nim c -r -o:target/livecore src/server.nim $@
	sleep 1
done
